steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',"-ldflags","-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn", '-t', 'gcr.io/$PROJECT_ID/xray-core-dev:$COMMIT_SHA', '.' ]
    id: build_image
  - name: 'gcr.io/cloud-builders/docker'
    args: [  'tag', 'gcr.io/$PROJECT_ID/xray-core-dev:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/xray-core-dev:latest' ]
    id: build_latest_image

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/xray-core-dev:$COMMIT_SHA']
    id: push_sha_image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/xray-core-dev:latest']
    id: push_latest_image
timeout: '1600s'
